FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y make build-essential libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev wget curl git llvm \
libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

RUN curl https://get.modular.com | sh - && \
modular auth mut_ca540c6480ac4f108c8ab174826aed07

RUN curl https://pyenv.run | bash
RUN pyenv install 3.10
RUN pyenv global 3.10.13
RUN modular install mojo

CMD ["python", "-m", "http.server"]