version: "3.9"

services:
  mojo-runner:
    container_name: mojo-runner
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - AUTH_KEY=1Auth_token
      no_cache : true
    ports:
      - 8888:8888 

    volumes:
      - .:/mojo
      
    working_dir: /mojo 
